name: Build and Publish HA Addon

on: [ workflow_dispatch ]
#on: [push, pull_request]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy files
        run: |
          rsync -a . ./ha_addon/src/ --exclude './ha_addon/'
          app_version=$(cat ./ha_addon/src/package.json | jq -r '.version')
          sed -i -e "s/_____APP_VERSION_____/${version}/" ./ha_addon/config.yaml
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --addon \
            --docker-hub ghcr.io/${{ github.actor }} \
            --image echonetlite2mqtt-addon/{arch} \
            --target /data/ha_addon \
