name: Build and Publish HA Addon

on: [ workflow_dispatch ]
#on: [push, pull_request]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    strategy:
        matrix:
          arch: ["aarch64", "amd64", "armv7"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Copy files
        run: |
          cp -r . ha_addon/src
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --addon \
            --${{ matrix.arch }} \
            --target /data/ha_addon \
